### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by deadtrickster** [deadtrickster/prometheus.ex#1]
Checklist for modules:
- [x] buckets;
- [x] collector;
- [x] model;
- [x] registry;
- [x] http;
- [x] protobuf;
- [x] text;
- [x] counter;
- [x] gauge;
- [x] histogram;
- [x] summary;

Checklist for pages:
 - [x] Overview;
 - [x] Time intervals;
 - [x] vm_memory_collector;
 - [x] vm_statistics_collector;
 - [x] vm_system_info_collector.
